### PR TITLE
bugfix: py3.7 ModuleNotFoundError: No module named 'utils'

### PR DESCRIPTION
**Pull request by MyKings**
Fix import error in py3.7

### CODE REVIEW

**Comment by wangoloj** [comment]
Your changes works very well for production https://pypi.org/project/python3-nmap/

When in the development I get the following errors

[Traceback (most recent call last):
  File "nmap3.py", line 29, in <module>
    from .utils import (get_nmap_path
ImportError: attempted relative import with no known parent package](url)

Is it really working for you?

**Comment by wangoloj** [comment]
Okay @MyKings  I have got the issue let me fix it now by merging your request.

**Comment by MyKings** [comment]
I recommend using absolute path import:

E.g:

```python
from nmap3.utils import get_nmap_path
```
In development mode you need to set `sys.path`.

```python
sys.path.append(os.path.dirname(os.path.realpath (__file__)))
```

**Comment by wangoloj** [comment]
Okay thank you for highlighting that, will update it in the next changes.

**Pull request merged**
